import NavBar from '@/components/NavBar'
import './globals.css'
import { Inter } from 'next/font/google'
import Home from './home/page'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Social Media',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <NavBar/>
        <Home/>
        {children}
      </body>
    </html>
  )
}
